### ISSUE TITLE
Improper Tag Capitalizations with RSS feed

### ISSUE THREAD

**Issue by mustafakamran98** [HiPhish/HiPhish.github.io#3]
When viewing the RSS feed through [this addon](https://addons.mozilla.org/en-US/firefox/addon/rsspreview/), the dates are missing. Checking via an [RSS validator](https://www.rssboard.org/rss-validator/check.cgi?url=https%3A%2F%2Fhiphish.github.io%2Fblog%2Frss.xml) reveals that some tags are not recognized like `pubdate`. According to the RSS specification, `pubDate` is indeed part of the specification, albeit with different capitalization.

![image](https://github.com/HiPhish/HiPhish.github.io/assets/27556124/eb1cdcb7-3da7-4b31-9946-da2a59fdc46c)
Screenshot of feed of website being viewed via the addon

![image](https://github.com/HiPhish/HiPhish.github.io/assets/27556124/fe08e196-eaa3-4f3b-8186-66a2379121b1)
For reference, this is how a feed is typically displayed with dates

**Comment by HiPhish** [comment]
Thank you for bringing that up, it should be fixed now. Turns out I was using the correct case, but my static site generator was down-casing all strings for whatever reason.

**Comment by mustafakamran98** [comment]
![image](https://github.com/HiPhish/HiPhish.github.io/assets/27556124/91b3d846-8f7b-4851-9910-fdfee3452e50)
Yes it seems fixed. Off-topic but I can't help but notice the typo with "rablings"

**Comment by HiPhish** [comment]
Ouch, that must be been there for years. It should be fixed now.

**Comment by mustafakamran98** [comment]
Sorry for the delayed reply but yes I can confirm it's fixed. Feel free to close.
